import SEOPage from './SEOPage'

export const AIVideoProduction = () => (
    <SEOPage
        title="AI Video Production Company | Cinematic Brand Intelligence"
        subheading="AI VIDEO PRODUCTION"
        intro="We engineer high-fidelity cinematic video systems using Veo3 and Sora 2, automating the creative lifecycle for global brand dominance."
        sections={[
            {
                heading: 'Enterprise AI Automation vs Traditional Solutions',
                body: 'Most traditional production studios rely on labor-intensive human lifecycles that introduce friction, delay, and inconsistency. Our AI video production systems replace these bottlenecks with clinical automation engines. By treating creative as an engineering problem, we deliver cinematic-grade brand assets with absolute technical precision and predictable scalability.',
                icon: '🎬'
            },
            {
                heading: 'Veo3 & Sora 2 Integration',
                body: 'Deployment of high-fidelity generative systems requires more than a prompt. We build the infrastructure that handles lighting, consistency, and narrative logic at scale. Our systems are designed for high-end enterprise needs where visual fidelity is non-negotiable. We integrate advanced diffusion models with proprietary prompt-engineering frameworks to deliver visual assets that were previously impossible without multi-million dollar budgets.',
                icon: '⚡'
            },
            {
                heading: 'Automated Creative Lifecycles',
                body: 'We automate the transition from script to screen. Our pipelines handle storyboarding, asset generation, and final cinematic assembly. This is not about partial automation; it is about building a clinical creative factory that scales with your growth. By treating creative production as an engineering problem, we remove the friction of human-led studio delays.',
                icon: '🔄'
            },
            {
                heading: 'Performance-Driven Creative Systems',
                body: 'Every visual asset generated by our systems is measured against performance signals. We bridge the gap between high-end cinematic production and performance marketing metrics. This ensures that every AI-generated frame isn\'t just beautiful—it is optimized for conversion and systemic brand retention.',
                icon: '📈'
            }
        ]}
        cta={{
            title: 'Ready for Visual Dominance?',
            text: 'Transition your creative production into a high-fidelity AI automation system.',
            btn: 'GET QUOTE'
        }}
        video="https://assets.mixkit.co/videos/preview/mixkit-futuristic-abstract-loop-of-blue-particles-73-large.mp4"
        structuredData={{
            "@context": "https://schema.org",
            "@type": "Service",
            "name": "AI Video Production",
            "provider": { "@type": "Organization", "name": "International Garudas" },
            "description": "High-fidelity AI video production using Veo3 and Sora 2 for enterprise brand campaigns."
        }}
    />
)

export const PoliticalIntelligence = () => (
    <SEOPage
        title="Political Campaign Technology | Intelligence & Data Platforms"
        subheading="POLITICAL INTELLIGENCE"
        intro="We architect Booth-level analytics, voter CRM systems, and constituency intelligence platforms for strategic political leadership."
        sections={[
            {
                heading: 'Political Campaign Intelligence Platforms — Mechanisms & Outcomes',
                body: 'Modern political victory is no longer about gut feeling; it is about architectural control of data. Our systems provide booth-level visibility into voter sentiment shifts and mobilization metrics. By mapping thousands of intelligence nodes across a constituency, we enable leaders to deploy narrative updates with surgical precision, ensuring winning outcomes through data dominance.',
                icon: '🏛️'
            },
            {
                heading: 'AI-Powered Voter CRM',
                body: 'Systemic voter engagement requires automated, personalized communication at scale. Our platforms integrate WhatsApp AI automation with voter data to create high-impact, hyper-relevant outreach systems. These platforms maintain persistent relationships with voters, ensuring your message is delivered and retained with clinical efficiency.',
                icon: '🗳️'
            },
            {
                heading: 'Booth-Level Intelligence Nodes',
                body: 'Precision winning happens at the booth level. We deploy localized intelligence nodes that monitor sentiment and mobilization in real-time. Our systems provide campaign leaders with a bird\'s-eye view of the political landscape, allowing for rapid-response tactical changes during critical election cycles.',
                icon: '📍'
            },
            {
                heading: 'Secure Campaign Infrastructure',
                body: 'Security is paramount in political technology. We build our platforms on secure, containerized cloud environments (GKE/Cloud Run) to ensure data integrity and operational continuity under extreme pressure. Our infrastructure is designed for the high-stakes environment of global political leadership.',
                icon: '🔒'
            }
        ]}
        cta={{
            title: 'Architect Your Victory',
            text: 'Control the narrative with infrastructure-level political intelligence.',
            btn: 'GET QUOTE'
        }}
        video="https://assets.mixkit.co/videos/preview/mixkit-abstract-technology-connection-dots-and-lines-loop-21151-large.mp4"
        structuredData={{
            "@context": "https://schema.org",
            "@type": "Service",
            "name": "Political Intelligence Platform",
            "provider": { "@type": "Organization", "name": "International Garudas" },
            "description": "Advanced political campaign technology and voter analytics platforms."
        }}
    />
)

export const WhatsAppAutomation = () => (
    <SEOPage
        title="WhatsApp AI Automation | Evolution API & Business Systems"
        subheading="WHATSAPP AUTOMATION"
        intro="Scale your business intelligence with Evolution API and n8n-powered WhatsApp automation systems designed for total customer acquisition."
        sections={[
            {
                heading: 'Intelligent Business Systems',
                body: 'We deploy high-performance WhatsApp AI automation that maintains context, handles complex inquiries, and drives conversions 24/7. Our systems use the Evolution API for stable, enterprise-grade integration, allowing businesses to maintain high-velocity communication without human bottlenecks.',
                icon: '💬'
            },
            {
                heading: 'Flow & Logic Orchestration',
                body: 'Using n8n and Gemini-powered logic, we architect communication flows that feel human but scale with machine efficiency. From customer support to automated sales funnels, we build the infrastructure for growth. Our logic engines can handle thousands of concurrent conversations while maintaining surgical precision in intent recognition.',
                icon: '🔄'
            },
            {
                heading: 'Conversational Intelligence ROI',
                body: 'WhatsApp automation is not just about chat; it is about acquisition. Our systems are designed to push users through custom-built funnels, qualifying leads and closing sales automatically. We measure ROI in every message, turning your communication channel into a high-performance growth engine.',
                icon: '💰'
            }
        ]}
        cta={{
            title: 'Automate Your Dominance',
            text: 'Deploy an intelligent WhatsApp infrastructure that never sleeps.',
            btn: 'GET QUOTE'
        }}
        video="https://videos.pexels.com/video-files/3129910/3129910-sd_640_360_25fps.mp4"
        structuredData={{
            "@context": "https://schema.org",
            "@type": "Service",
            "name": "WhatsApp AI Automation",
            "provider": { "@type": "Organization", "name": "International Garudas" },
            "description": "Enterprise WhatsApp automation systems using Evolution API and AI logic."
        }}
    />
)

export const AISaaSDeployment = () => (
    <SEOPage
        title="AI SaaS Development Company | Full-Stack Product Engineering"
        subheading="AI SAAS DEVELOPMENT"
        intro="We engineer high-fidelity AI products from schema design to Cloud Run deployment, building the software foundation for next-gen organizations."
        sections={[
            {
                heading: 'Architectural Excellence',
                body: 'As an AI SaaS development company, we focus on building scalable, security-first product infrastructures. We use GKE, Cloud Run, and Supabase to ensure your platform handles massive scale with clinical efficiency. We don\'t just write code; we architect systems that are built to withstand the demands of global enterprise usage.',
                icon: '⚙️'
            },
            {
                heading: 'AI-First Product Logic',
                body: 'We don\'t just add AI; we build products around it. Our engineering team specializes in integrating LLMs and generative systems into core product workflows, creating unique market advantages for our partners. This deep-node integration ensures that AI is not a feature, but the fundamental engine of the product.',
                icon: '🧠'
            },
            {
                heading: 'Cloud-Native Scalability',
                body: 'Every product we build is cloud-native from day one. We bridge the gap between complex AI logic and reliable software delivery, ensuring that your SaaS platform can scale from zero to millions of users without architectural re-engineering. Our focus is on long-term product longevity and operational stability.',
                icon: '☁️'
            }
        ]}
        cta={{
            title: 'Build Your Software Legacy',
            text: 'Transform your vision into a high-performance AI SaaS platform.',
            btn: 'GET QUOTE'
        }}
        video="https://assets.mixkit.co/videos/preview/mixkit-abstract-technology-connection-dots-and-lines-loop-21151-large.mp4"
        structuredData={{
            "@context": "https://schema.org",
            "@type": "Service",
            "name": "AI SaaS Development",
            "provider": { "@type": "Organization", "name": "International Garudas" },
            "description": "Full-stack AI SaaS development and product engineering services."
        }}
    />
)

export const PerformanceMarketing = () => (
    <SEOPage
        title="Performance Marketing Systems | AI Marketing Infrastructure"
        subheading="PERFORMANCE MARKETING"
        intro="Deploy mathematical performance engines optimized for ROAS and systemic acquisition across every digital platform."
        sections={[
            {
                heading: 'Why AI Systems Infrastructure Outperforms Traditional Marketing',
                body: 'Traditional digital marketing focuses on siloed campaigns and surface-level engagement. We engineer performance marketing infrastructure that integrates data signals across the entire acquisition lifecycle. By replacing manual optimization with AI-powered mathematical engines, we achieve ROAS and scale that generic agencies cannot match. This is systems-driven growth for elite enterprises.',
                icon: '📈'
            },
            {
                heading: 'Creative Automation at Scale',
                body: 'High-performance campaigns require massive creative variation. We integrate our AI video and image pipelines with paid media workflows to produce thousands of high-converting assets automatically. This allows for rapid A/B testing at a scale that human creative teams cannot match.',
                icon: '🎨'
            },
            {
                heading: 'Real-Time Signal Optimization',
                body: 'Our systems listen to real-time market signals and adjust bids and creative deployments accordingly. This surgical-grade optimization ensures that your brand remains dominant in competitive auction environments across Google, Meta, and LinkedIn.',
                icon: '📡'
            }
        ]}
        cta={{
            title: 'Command Your Growth',
            text: 'Switch to a mathematical performance system designed for dominance.',
            btn: 'GET QUOTE'
        }}
        video="https://assets.mixkit.co/videos/preview/mixkit-slow-motion-of-abstract-blue-lines-and-particles-20412-large.mp4"
        structuredData={{
            "@context": "https://schema.org",
            "@type": "Service",
            "name": "Performance Marketing Systems",
            "provider": { "@type": "Organization", "name": "International Garudas" },
            "description": "AI-powered performance marketing and creative automation infrastructure."
        }}
    />
)
